# Generated by Django 5.1.1 on 2024-10-05 14:43

import Cyber_Track.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_Track', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defamationcomplaint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='finiancialfraudcomplaint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='othercomplaint',
            name='id',
        ),
        migrations.RemoveField(
            model_name='socialmediahackcomplaint',
            name='id',
        ),
        migrations.AlterField(
            model_name='defamationcomplaint',
            name='complaint_id',
            field=models.CharField(default=Cyber_Track.models.generate_unique_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='finiancialfraudcomplaint',
            name='complaint_id',
            field=models.CharField(default=Cyber_Track.models.generate_unique_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='othercomplaint',
            name='complaint_id',
            field=models.CharField(default=Cyber_Track.models.generate_unique_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmediahackcomplaint',
            name='complaint_id',
            field=models.CharField(default=Cyber_Track.models.generate_unique_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
