# Generated by Django 5.1.1 on 2024-10-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_Track', '0002_remove_defamationcomplaint_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defamationcomplaint',
            old_name='Victim_Name',
            new_name='victim_Name',
        ),
        migrations.RenameField(
            model_name='finiancialfraudcomplaint',
            old_name='Victim_Name',
            new_name='victim_Name',
        ),
        migrations.RenameField(
            model_name='othercomplaint',
            old_name='Victim_Name',
            new_name='victim_Name',
        ),
        migrations.RenameField(
            model_name='socialmediahackcomplaint',
            old_name='Victim_Name',
            new_name='victim_Name',
        ),
    ]
