# Generated by Django 5.1.1 on 2024-10-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_Track', '0003_rename_victim_name_defamationcomplaint_victim_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiniancialFraudComplaint',
            new_name='FinancialFraudComplaint',
        ),
    ]
