# Generated by Django 5.1.1 on 2024-10-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cyber_Track', '0004_rename_finiancialfraudcomplaint_financialfraudcomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_action', 'In Action'), ('scam', 'Scam'), ('resolved', 'Resolved')], default='pending', max_length=50),
        ),
    ]
