# Generated by Django 5.1.2 on 2024-10-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_id_user_official_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='official_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
