# Generated by Django 5.1.2 on 2024-10-15 10:38

import complaints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_defamationcomplaint_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defamationcomplaint',
            name='complaint_id',
            field=models.CharField(default=complaints.models.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='financialfraudcomplaint',
            name='complaint_id',
            field=models.CharField(default=complaints.models.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='othercomplaint',
            name='complaint_id',
            field=models.CharField(default=complaints.models.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='socialmediahackcomplaint',
            name='complaint_id',
            field=models.CharField(default=complaints.models.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
