# Generated by Django 5.1.2 on 2024-10-15 11:11

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_defamationcomplaint_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defamationcomplaint',
            name='guardian_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='financialfraudcomplaint',
            name='guardian_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='othercomplaint',
            name='guardian_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='socialmediahackcomplaint',
            name='guardian_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
