# Generated by Django 5.1.2 on 2024-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_defamationcomplaint_guardian_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defamationcomplaint',
            name='evidence_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialfraudcomplaint',
            name='evidence_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='othercomplaint',
            name='evidence_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialmediahackcomplaint',
            name='evidence_links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
