# Generated by Django 5.1.2 on 2024-10-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_defamationcomplaint_evidence_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defamationcomplaint',
            name='id_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='financialfraudcomplaint',
            name='id_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='othercomplaint',
            name='id_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmediahackcomplaint',
            name='id_url',
            field=models.URLField(max_length=100),
        ),
    ]
