# Generated by Django 5.1.2 on 2024-10-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_defamationcomplaint_id_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defamationcomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Action', 'In Action'), ('Scam', 'Scam'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='financialfraudcomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Action', 'In Action'), ('Scam', 'Scam'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='othercomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Action', 'In Action'), ('Scam', 'Scam'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='socialmediahackcomplaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Action', 'In Action'), ('Scam', 'Scam'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default=1),
        ),
    ]
