
# Generated by Django 5.1.2 on 2024-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_defamationcomplaint_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialfraudcomplaint',
            name='amount',
            field=models.PositiveBigIntegerField(),
        ),
    ]
